/* 天衡 V7：今日行動策略層（今日一句策略／感情／事業／最佳時段／風險） */
(function(){'use strict';
function text(){return document.body?document.body.innerText:''}
function clean(s){return (s||'').replace(/\s+/g,' ').trim()}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function score(label,fb){var m=text().match(new RegExp(label+'[^0-9]{0,20}(\\d{2,3})'));return m?clamp(+m[1],35,96):fb}
function overall(){var m=text().match(/(\d{2,3})[\s\n]*命\s*運\s*綜\s*評/);return m?clamp(+m[1],35,96):72}
function pickTime(){var t=text();var m=t.match(/吉時[^\n：:]{0,8}[：:]?\s*([^\n]{2,36})/);if(m)return clean(m[1]);var h=new Date().getHours();if(h<11)return '上午 09:00–11:00';if(h<16)return '下午 13:00–15:00';return '晚間 19:00–21:00'}
function todayData(){var o=overall(),love=score('感情',clamp(o+2,45,93)),career=score('事業',clamp(o+1,45,93)),wealth=score('財運',clamp(o-1,43,92));var best=Math.max(love,career,wealth);var strategy,rel,work,risk;if(best===career){strategy=career>=78?'今天適合把重要事情往前推：主動聯絡、談合作、確認條件，比等待更有利。':'今天適合整理優先順序，把最能帶來結果的一件事先完成。';}else if(best===love){strategy=love>=78?'今天的人際與感情氣場較活，適合主動表達、約見或修復關係。':'今天宜用穩定互動累積好感，少猜、多問、多確認。';}else{strategy=wealth>=78?'今天適合處理報價、收款、成本與資源配置，讓財務決定回到數字。':'今天先守現金流與支出節奏，不為短期誘惑改變原本規劃。';}
rel=love>=78?'感情上宜主動，但避免一次說太滿；留一點空間，互動更自然。':love>=64?'適合關心、傾聽與安排短時間相處，重點是讓對方感到被理解。':'感情宜慢，不急著定義關係；今天先避免情緒化訊息與翻舊帳。';
work=career>=78?'把需要拍板、提案、談條件的工作放前面；可主動爭取資源與回覆。':career>=64?'適合整理流程、回訪舊客、補完未完成事項；穩定推進勝過突然改方向。':'避免衝動離職或重押新案；先做小規模驗證，再決定是否擴大。';
risk=(career>=80&&wealth<68)?'事業衝得快，但財務承載較慢；今天避免為了搶進度忽略成本。':(love>=80&&career<66)?'人際感受較強，別讓情緒影響工作判斷；重要決定先回到事實與數字。':'今天最大的風險不是運勢差，而是同時做太多事；保留餘裕反而更順。';return{o:o,love:love,career:career,wealth:wealth,strategy:strategy,rel:rel,work:work,risk:risk,time:pickTime()}}
function style(){if(document.getElementById('th-v7-style'))return;var s=document.createElement('style');s.id='th-v7-style';s.textContent='\
#th-v7-today{margin:18px auto 26px;max-width:960px;color:#eadfca;font-family:inherit}.th7-card{position:relative;overflow:hidden;border:1px solid rgba(210,169,87,.58);border-radius:24px;padding:22px 20px;background:radial-gradient(circle at 92% 0%,rgba(211,169,87,.13),transparent 28%),linear-gradient(145deg,rgba(29,20,35,.97),rgba(7,9,15,.99));box-shadow:0 18px 42px rgba(0,0,0,.25)}.th7-k{color:#d9b86d;font-size:12px;letter-spacing:.28em;text-align:center}.th7-title{font-size:24px;color:#f1e3c8;text-align:center;letter-spacing:.12em;margin:7px 0 16px}.th7-strategy{padding:16px 17px;border-radius:16px;background:rgba(207,166,82,.065);border:1px solid rgba(207,166,82,.25);color:#f0dfba;font-size:16px;line-height:1.8;text-align:center}.th7-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.th7-mini{padding:13px 11px;border-radius:14px;background:rgba(255,255,255,.025);border:1px solid rgba(194,151,76,.16);text-align:center}.th7-mini small{display:block;color:#9a8f7d;font-size:11px;margin-bottom:5px}.th7-mini b{font-size:22px;color:#e2c47e;font-weight:500}.th7-actions{display:grid;grid-template-columns:1fr 1fr;gap:11px}.th7-action{padding:15px;border-radius:15px;background:rgba(0,0,0,.18);border:1px solid rgba(194,151,76,.16)}.th7-action b{display:block;color:#cda85f;font-size:12px;letter-spacing:.14em;margin-bottom:6px}.th7-action p{margin:0;color:#d8ccba;font-size:14px;line-height:1.75}.th7-bottom{display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:11px}.th7-time,.th7-risk{padding:14px 15px;border-radius:15px;border:1px solid rgba(194,151,76,.16);font-size:13px;line-height:1.75}.th7-time{background:rgba(111,163,126,.055);color:#cfe0d4}.th7-risk{background:rgba(173,105,91,.055);color:#d7b0a7}.th7-time b,.th7-risk b{display:block;font-size:11px;letter-spacing:.14em;margin-bottom:5px}.th7-time b{color:#8fb39a}.th7-risk b{color:#c98275}.th7-note{text-align:center;color:#81786d;font-size:10.5px;line-height:1.6;margin-top:12px}@media(max-width:700px){.th7-card{padding:20px 14px;border-radius:20px}.th7-title{font-size:21px}.th7-strategy{font-size:15px}.th7-actions,.th7-bottom{grid-template-columns:1fr}.th7-grid{gap:7px}.th7-mini{padding:11px 7px}.th7-mini b{font-size:20px}}';document.head.appendChild(s)}
function anchor(){var nodes=document.querySelectorAll('h1,h2,h3,h4,section,div');for(var i=0;i<nodes.length;i++){var t=(nodes[i].textContent||'').replace(/\s+/g,'');if((t.indexOf('今日運勢')!==-1||t.indexOf('今日天衡')!==-1)&&t.length<80)return nodes[i]}var r=document.getElementById('result');return r?r.firstElementChild:null}
function render(){if(document.getElementById('th-v7-today'))return;if(text().indexOf('命運綜評')===-1)return;var a=anchor();if(!a||!a.parentNode)return;var d=todayData();var sec=document.createElement('section');sec.id='th-v7-today';sec.innerHTML='<div class="th7-card"><div class="th7-k">今 日 天 衡 ・ 行 動 指 引</div><div class="th7-title">今天最值得做的一件事</div><div class="th7-strategy">'+d.strategy+'</div><div class="th7-grid"><div class="th7-mini"><small>感情</small><b>'+d.love+'</b></div><div class="th7-mini"><small>事業</small><b>'+d.career+'</b></div><div class="th7-mini"><small>財運</small><b>'+d.wealth+'</b></div></div><div class="th7-actions"><div class="th7-action"><b>感 情 行 動</b><p>'+d.rel+'</p></div><div class="th7-action"><b>事 業 行 動</b><p>'+d.work+'</p></div></div><div class="th7-bottom"><div class="th7-time"><b>最佳行動時段</b>'+d.time+'</div><div class="th7-risk"><b>今日風險提醒</b>'+d.risk+'</div></div><div class="th7-note">依目前命盤頁的今日分數與既有吉時資訊整理為行動建議；屬趨勢參考，不代表事件必然發生。</div></div>';var host=a.closest('section,article')||a;a.parentNode.insertBefore(sec,host.nextSibling)}
function run(){try{style();render()}catch(e){}}
var tm;function schedule(){clearTimeout(tm);tm=setTimeout(run,280)}
if(document.body){new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()}else document.addEventListener('DOMContentLoaded',function(){new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()})
})();