/* 天衡 V9：LINE 入口更新為「三寶爸的命理分析 @788ldzke」並統一 CTA */
(function(){'use strict';
var LINE_ID='@788ldzke';
var LINE_NAME='三寶爸的命理分析';
var LINE_URL='https://line.me/R/ti/p/@788ldzke';
function addStyle(){if(document.getElementById('th-v9-line-style'))return;var s=document.createElement('style');s.id='th-v9-line-style';s.textContent='\
.th-line-entry{margin:22px auto 10px;max-width:960px;padding:18px;border:1px solid rgba(216,183,104,.52);border-radius:20px;background:radial-gradient(circle at 12% 0%,rgba(216,183,104,.11),transparent 30%),linear-gradient(148deg,rgba(26,19,33,.97),rgba(7,8,14,.99));box-shadow:0 16px 40px rgba(0,0,0,.26)}\
.th-line-profile{display:flex;align-items:center;gap:14px;margin-bottom:14px}.th-line-avatar{width:58px;height:58px;flex:0 0 58px;border-radius:50%;display:grid;place-items:center;border:1px solid rgba(216,183,104,.68);color:#f1d996;font-size:22px;background:radial-gradient(circle,rgba(216,183,104,.16),rgba(16,12,22,.96));box-shadow:0 0 20px rgba(216,183,104,.12)}\
.th-line-copy{min-width:0;flex:1}.th-line-name{color:#f0e3c8;font-size:20px;letter-spacing:.06em}.th-line-id{margin-top:4px;color:#cbb27d;font-size:14px;letter-spacing:.03em}.th-line-arrow{color:#d9b768;font-size:28px;line-height:1}.th-line-stats{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:12px 0}.th-line-stat{padding:12px 13px;border:1px solid rgba(216,183,104,.18);border-radius:13px;background:rgba(255,255,255,.025);display:flex;align-items:center;justify-content:space-between;color:#d8cbb7;font-size:13px}.th-line-stat b{color:#e6c87e;font-size:18px;font-weight:500}.th-line-cta{display:flex;align-items:center;justify-content:center;gap:10px;width:100%;min-height:54px;border-radius:999px;background:linear-gradient(135deg,#06c755,#00a844);color:#fff!important;text-decoration:none!important;font-size:17px;font-weight:700;letter-spacing:.05em;box-shadow:0 12px 28px rgba(0,190,80,.22),inset 0 1px 0 rgba(255,255,255,.22)}.th-line-cta:active{transform:scale(.985)}.th-line-note{text-align:center;margin-top:10px;color:#8f8577;font-size:11px;line-height:1.65}@media(max-width:430px){.th-line-entry{margin-left:0;margin-right:0;padding:16px 14px;border-radius:18px}.th-line-name{font-size:18px}.th-line-avatar{width:52px;height:52px;flex-basis:52px}.th-line-stats{grid-template-columns:1fr}.th-line-cta{font-size:16px}}';document.head.appendChild(s)}
function replaceExisting(){var nodes=document.querySelectorAll('a,button');for(var i=0;i<nodes.length;i++){var n=nodes[i],t=(n.textContent||'').replace(/\s+/g,'');if(t.indexOf('LINE')===-1)continue;if(n.tagName==='A'){n.href=LINE_URL;n.target='_blank';n.rel='noopener';}if(/加入LINE|領取完整命書|完整命書|跟我說/.test(t)){n.textContent='加入 LINE 領取完整命書';if(n.tagName!=='A'&&!n.dataset.thLineHook){n.dataset.thLineHook='1';n.addEventListener('click',function(){window.open(LINE_URL,'_blank','noopener')});}}}
var txtNodes=document.querySelectorAll('div,p,span');for(var j=0;j<txtNodes.length;j++){var x=txtNodes[j];if(x.children.length)continue;var tx=x.textContent||'';if(/@[0-9A-Za-z_-]{4,}/.test(tx)&&tx.toUpperCase().indexOf('LINE')!==-1){x.textContent=tx.replace(/@[0-9A-Za-z_-]{4,}/g,LINE_ID)}}}
function findResultHost(){var r=document.getElementById('result');if(r&&r.classList.contains('show'))return r;return null}
function insertCard(){if(document.getElementById('th-line-entry'))return;var host=findResultHost();if(!host)return;var sec=document.createElement('section');sec.id='th-line-entry';sec.className='th-line-entry';sec.innerHTML='<div class="th-line-profile"><div class="th-line-avatar" aria-hidden="true">衡</div><div class="th-line-copy"><div class="th-line-name">'+LINE_NAME+'</div><div class="th-line-id">LINE 官方帳號 '+LINE_ID+'</div></div><div class="th-line-arrow">›</div></div><div class="th-line-stats"><div class="th-line-stat"><span>命書諮詢入口</span><b>LINE</b></div><div class="th-line-stat"><span>完整解析與後續提問</span><b>→</b></div></div><a class="th-line-cta" href="'+LINE_URL+'" target="_blank" rel="noopener" aria-label="加入 '+LINE_NAME+' LINE"><span>LINE</span><span>加入 LINE 領取完整命書</span></a><div class="th-line-note">LINE：'+LINE_ID+'・點擊後直接開啟好友加入頁</div>';
var support=document.getElementById('support');if(support&&support.parentNode===host.parentNode){host.parentNode.insertBefore(sec,support);}else{host.appendChild(sec)}}
function run(){try{addStyle();replaceExisting();insertCard()}catch(e){console.error('[天衡 V9 LINE]',e)}}
var tm;function schedule(){clearTimeout(tm);tm=setTimeout(run,220)}
if(document.body){new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()}else document.addEventListener('DOMContentLoaded',function(){new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()})
})();
