/* 天衡 V11：四大命書線上付款／後端驗證／自動解鎖 */
(function(){'use strict';
var PAY_API='https://tianheng-pay.rhtm9y855y.workers.dev';
var KEY='th_unlock_tokens_v1';
function getTokens(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function saveToken(gate,token){var t=getTokens();t[gate]=token;localStorage.setItem(KEY,JSON.stringify(t))}
function formPost(action,fields){var f=document.createElement('form');f.method='POST';f.action=action;f.style.display='none';Object.keys(fields).forEach(function(k){var i=document.createElement('input');i.type='hidden';i.name=k;i.value=fields[k];f.appendChild(i)});document.body.appendChild(f);f.submit()}
async function createPayment(gate){var r=await fetch(PAY_API+'/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({gate:gate})});if(!r.ok)throw new Error('payment_create_failed');var d=await r.json();if(!d.ok)throw new Error(d.error||'payment_create_failed');try{sessionStorage.setItem('th_pending_order',d.order)}catch(e){}formPost(d.action,d.fields)}
async function status(order){var r=await fetch(PAY_API+'/status?order='+encodeURIComponent(order),{cache:'no-store'});if(!r.ok)return null;return await r.json()}
async function verifySaved(){var all=getTokens(),gates=Object.keys(all);for(var i=0;i<gates.length;i++){try{var r=await fetch(PAY_API+'/verify?token='+encodeURIComponent(all[gates[i]]),{cache:'no-store'});var d=await r.json();if(d.ok)markUnlocked(d.gate)}catch(e){}}}
function markUnlocked(gate){var card=document.querySelector('.th10-gate[data-key="'+gate+'"]');if(card){card.classList.add('th11-unlocked');card.setAttribute('data-unlocked','1');var c=card.querySelector('.th10-check');if(c)c.textContent='✓';var tag=card.querySelector('.th10-tag');if(tag&&!/已解鎖/.test(tag.textContent))tag.textContent='已解鎖・可查看完整命書';}
var btn=document.getElementById('th10-open');if(btn){var sel=document.querySelector('.th10-gate.is-selected');if(sel&&sel.dataset.key===gate){btn.disabled=false;btn.textContent='查看已解鎖命書'}}}
function addStyle(){if(document.getElementById('th-v11-style'))return;var s=document.createElement('style');s.id='th-v11-style';s.textContent='.th10-gate.th11-unlocked{border-color:rgba(85,190,125,.72)!important;box-shadow:0 0 0 1px rgba(85,190,125,.12),0 12px 28px rgba(0,0,0,.18)}.th10-gate.th11-unlocked .th10-check{background:#55be7d!important;border-color:#83d7a2!important;color:#07120b!important}.th11-payhint{margin-top:10px;text-align:center;color:#9d907e;font-size:11px;line-height:1.65}.th11-online{width:100%;min-height:50px;margin-top:10px;border:1px solid #e0bd6c;border-radius:999px;background:linear-gradient(135deg,#d7b45f,#a36e2d);color:#160f09;font-family:inherit;font-weight:700;font-size:15px;cursor:pointer}';document.head.appendChild(s)}
function hook(){var modal=document.getElementById('th10-modal'),lineBtn=document.getElementById('th10-line');if(!modal||modal.dataset.th11)return;modal.dataset.th11='1';var panel=modal.querySelector('.th10-panel');if(!panel)return;var b=document.createElement('button');b.className='th11-online';b.id='th11-online';b.textContent='線上付款 NT$99・付款後自動解鎖';var hint=document.createElement('div');hint.className='th11-payhint';hint.textContent='信用卡／ATM／超商等實際可用方式依金流商店設定為準。付款成功由後端驗證，不需人工回傳末五碼。';var acts=panel.querySelector('.th10-actions');if(acts){acts.parentNode.insertBefore(b,acts);acts.parentNode.insertBefore(hint,acts)}else panel.appendChild(b);
b.addEventListener('click',function(){var sel=document.querySelector('.th10-gate.is-selected');if(!sel)return;b.disabled=true;b.textContent='正在建立安全訂單…';createPayment(sel.dataset.key).catch(function(){b.disabled=false;b.textContent='線上付款暫未啟用・可先使用轉帳';alert('線上金流後端尚未完成部署或設定，請先使用原本轉帳方式。')})});
if(lineBtn)lineBtn.textContent='人工轉帳後回傳末五碼';}
async function handleReturn(){var q=new URLSearchParams(location.search),order=q.get('order');if(!order)return;for(var i=0;i<8;i++){var d=await status(order);if(d&&d.status==='paid'&&d.token){saveToken(d.gate,d.token);markUnlocked(d.gate);try{history.replaceState({},'',location.pathname)}catch(e){}alert('付款驗證完成，'+({love:'感情',career:'事業',health:'健康',wealth:'財富'}[d.gate]||'此項')+'深度命書已解鎖。');return}await new Promise(function(r){setTimeout(r,1200)})}}
function run(){try{addStyle();hook();verifySaved();handleReturn()}catch(e){}}
var tm;function schedule(){clearTimeout(tm);tm=setTimeout(run,320)}
if(document.body){new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()}else document.addEventListener('DOMContentLoaded',function(){new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()})
})();
