/* 天衡 V6：2026 下半年月運時間軸（感情／事業／財運） */
(function(){'use strict';
function text(){return document.body?document.body.innerText:''}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function score(label,fb){var m=text().match(new RegExp(label+'[^0-9]{0,20}(\\d{2,3})'));return m?clamp(+m[1],35,96):fb}
function overall(){var m=text().match(/(\d{2,3})[\s\n]*命\s*運\s*綜\s*評/);return m?clamp(+m[1],35,96):72}
function weak(){var m=text().match(/喜用神宜補([木火土金水])/);return m?m[1]:'木'}
var GEN={木:'火',火:'土',土:'金',金:'水',水:'木'};
var CTRL={木:'土',土:'水',水:'火',火:'金',金:'木'};
function elemAdj(monthElem,fav){if(monthElem===fav)return 5;if(GEN[monthElem]===fav)return 3;if(GEN[fav]===monthElem)return 1;if(CTRL[monthElem]===fav)return-5;if(CTRL[fav]===monthElem)return-2;return 0}
function tier(s){return s>=82?'旺':s>=72?'漸旺':s>=62?'平穩':s>=52?'守成':'蓄勢'}
function arrow(s,b){return s>=b+3?'↑':s<=b-3?'↓':'→'}
function monthData(){var o=overall(),love=score('感情',clamp(o+3,45,92)),career=score('事業',clamp(o+1,45,92)),wealth=score('財運',clamp(career-2,42,92)),fav=weak();
var months=[{m:9,e:'金',name:'九月'},{m:10,e:'金',name:'十月'},{m:11,e:'水',name:'十一月'},{m:12,e:'水',name:'十二月'}];
return months.map(function(x,i){var a=elemAdj(x.e,fav),phase=[-1,2,0,3][i];var l=clamp(love+a+phase,42,95),c=clamp(career+a+([2,0,3,-1][i]),42,95),w=clamp(wealth+a+([0,3,-1,2][i]),42,95);var best=Math.max(l,c,w),focus=best===c?'事業':best===l?'感情':'財運';var action=focus==='事業'?(c>=75?'適合主動談合作、推案與爭取資源。':'先整理流程與基本盤，再放大成果。'):focus==='感情'?(l>=75?'適合主動安排相處、表達心意與修復關係。':'放慢節奏，先觀察互動品質與安全感。'):(w>=75?'適合放大穩定收入來源，但仍避免追高與重押。':'以守現金流、降低無效支出為優先。');return{x:x,l:l,c:c,w:w,focus:focus,action:action,base:{l:love,c:career,w:wealth}}})}
function style(){if(document.getElementById('th-v6-style'))return;var s=document.createElement('style');s.id='th-v6-style';s.textContent='\
#th-v6-timeline{margin:28px auto;max-width:960px;color:#e8dfcf;font-family:inherit}.th6-wrap{padding:24px 20px;border-radius:24px;border:1px solid rgba(201,160,78,.52);background:linear-gradient(150deg,rgba(26,19,32,.97),rgba(7,8,14,.98));box-shadow:0 18px 42px rgba(0,0,0,.23)}.th6-k{text-align:center;color:#d9b86f;letter-spacing:.28em;font-size:12px}.th6-title{text-align:center;color:#f1e4c9;font-size:24px;letter-spacing:.12em;margin:8px 0 8px}.th6-sub{text-align:center;color:#918675;font-size:12px;line-height:1.7;margin-bottom:18px}.th6-months{display:grid;grid-template-columns:repeat(4,1fr);gap:11px}.th6-month{border:1px solid rgba(194,151,75,.24);background:rgba(255,255,255,.025);border-radius:17px;padding:14px 12px;cursor:pointer;transition:.2s}.th6-month:hover,.th6-month.is-open{border-color:rgba(224,185,103,.65);transform:translateY(-1px);background:rgba(198,157,78,.06)}.th6-mhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:11px}.th6-mname{color:#e8d6ad;font-size:16px;letter-spacing:.08em}.th6-elem{font-size:11px;color:#7fa88c;border:1px solid rgba(111,163,126,.45);border-radius:999px;padding:3px 8px}.th6-row{display:grid;grid-template-columns:40px 1fr 30px;align-items:center;gap:7px;margin:9px 0;font-size:11px}.th6-row span:first-child{color:#a99c89}.th6-bar{height:5px;background:#2a2022;border-radius:99px;overflow:hidden}.th6-bar i{display:block;height:100%;background:linear-gradient(90deg,#9d7841,#dfbd68);border-radius:99px}.th6-num{color:#d9c18c;text-align:right}.th6-focus{margin-top:11px;padding-top:10px;border-top:1px solid rgba(190,151,82,.15);color:#c9ab6b;font-size:12px}.th6-detail{margin-top:14px;padding:16px;border-radius:16px;background:rgba(0,0,0,.18);border:1px solid rgba(199,159,84,.18);display:none}.th6-month.is-open .th6-detail{display:block}.th6-detail p{margin:0;color:#d4c8b8;font-size:13px;line-height:1.75}.th6-legend{display:flex;justify-content:center;gap:14px;flex-wrap:wrap;margin-top:16px;color:#857b70;font-size:11px}.th6-note{text-align:center;color:#7e766e;font-size:11px;line-height:1.65;margin-top:14px}@media(max-width:700px){.th6-wrap{padding:20px 14px;border-radius:20px}.th6-title{font-size:21px}.th6-months{grid-template-columns:1fr 1fr;gap:9px}.th6-month{padding:13px 11px}.th6-mname{font-size:15px}}';document.head.appendChild(s)}
function anchor(){var v4=document.getElementById('th-v4-report');if(v4)return v4;var cross=document.getElementById('th-v5-cross');if(cross)return cross;var ns=document.querySelectorAll('h1,h2,h3,h4,section,div');for(var i=0;i<ns.length;i++){var t=(ns[i].textContent||'').replace(/\s+/g,'');if(t.indexOf('九維詳解')!==-1&&t.length<30)return ns[i]}return null}
function row(label,val){return '<div class="th6-row"><span>'+label+'</span><div class="th6-bar"><i style="width:'+val+'%"></i></div><b class="th6-num">'+val+'</b></div>'}
function render(){if(document.getElementById('th-v6-timeline'))return;var a=anchor();if(!a||!a.parentNode||text().indexOf('命運綜評')===-1)return;var data=monthData();var sec=document.createElement('section');sec.id='th-v6-timeline';sec.innerHTML='<div class="th6-wrap"><div class="th6-k">2026 下 半 年 ・ 月 運 導 航</div><div class="th6-title">感情 × 事業 × 財運時間軸</div><div class="th6-sub">點月份可展開行動建議；分數為既有命盤與喜用五行交叉出的相對趨勢。</div><div class="th6-months">'+data.map(function(d){return '<article class="th6-month" tabindex="0"><div class="th6-mhead"><div class="th6-mname">'+d.x.name+'</div><span class="th6-elem">'+d.x.e+'氣</span></div>'+row('感情',d.l)+row('事業',d.c)+row('財運',d.w)+'<div class="th6-focus">本月重點：'+d.focus+' '+arrow(d.focus==='感情'?d.l:d.focus==='事業'?d.c:d.w,d.focus==='感情'?d.base.l:d.focus==='事業'?d.base.c:d.base.w)+'</div><div class="th6-detail"><p><b style="color:#ddb96c">'+tier(Math.max(d.l,d.c,d.w))+'：</b>'+d.action+'</p></div></article>'}).join('')+'</div><div class="th6-legend"><span>↑ 比目前更有利</span><span>→ 節奏相近</span><span>↓ 宜守成</span></div><div class="th6-note">命理推演提供趨勢與自我整理參考，不代表特定事件必然發生；重大財務、職涯與關係決定仍應結合現實條件判斷。</div></div>';
a.parentNode.insertBefore(sec,a.nextSibling);var cards=sec.querySelectorAll('.th6-month');for(var i=0;i<cards.length;i++){cards[i].addEventListener('click',function(){this.classList.toggle('is-open')});cards[i].addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();this.classList.toggle('is-open')}})}}
function run(){try{style();render()}catch(e){}}
var tm;function schedule(){clearTimeout(tm);tm=setTimeout(run,300)}
if(document.body){new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()}else document.addEventListener('DOMContentLoaded',function(){new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()})
})();